version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./node-graphql
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://post_1qge_user:ASt4DhcVEVkR40meRMd0Y1Lkj1RFFDrx@dpg-cqf0uso8fa8c73egpipg-a.oregon-postgres.render.com/post_1qge
      - PORT=8000
